# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_dtm_cpp <- function(text, stopwords, remove_stopwords = TRUE) {
    .Call(`_opttext_fast_dtm_cpp`, text, stopwords, remove_stopwords)
}

cpp_lowercase <- function(texts) {
    .Call(`_opttext_cpp_lowercase`, texts)
}

